# Generated by Django 5.2.17 on 2026-10-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='tests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
