# Generated by Django 5.2.17 on 2026-10-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StarterItem',
            new_name='Mission',
        ),
    ]
