# Generated by Django 5.2.17 on 2026-10-01 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_starteritem_mission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='is_active',
        ),
        migrations.AddField(
            model_name='mission',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle', to='core.mission')),
            ],
        ),
    ]
