# Generated by Django 5.2.17 on 2026-10-01 19:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('summary', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('scene', models.TextField(help_text='What the close-up picture shows.')),
                ('image_url', models.CharField(blank=True, max_length=300)),
                ('prompt', models.TextField(help_text='What the player is asked to do here.')),
                ('map_level', models.PositiveSmallIntegerField(blank=True, help_text='Map level the player must solve before choosing. Leave blank for story-only nodes.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('success_text', models.TextField(blank=True, help_text='Shown after the challenge is solved.')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='missions.mission')),
            ],
            options={
                'ordering': ['mission', 'id'],
            },
        ),
        migrations.AddField(
            model_name='mission',
            name='start_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='missions.node'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=5)),
                ('label', models.CharField(max_length=120)),
                ('next_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_choices', to='missions.node')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='missions.node')),
            ],
            options={
                'ordering': ['node', 'side'],
                'constraints': [models.UniqueConstraint(fields=('node', 'side'), name='one_choice_per_side')],
            },
        ),
    ]
